# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-example-module
  description: Example Terraform Module Scaffolding
  homepage: https://cloudposse.com/accelerate
  topics: ""

environments:
  - name: release2
    deployment_branch_policy:
      custom_branches:
        - main
        - release/**
        - *.*.*
        - v*
