---
name: feature-branch
on:
  pull_request:
    branches:
      - main
      - release/v*
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  id-token: write
  contents: write

jobs:
  terraform-module:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/feature-branch.yml@readme-update
    secrets: inherit
