name: Run Linting Checks

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: 1.19
  TESTS_DIR: test/src
  REPORTER: local

jobs:
  golang:
    name: reviewdog/golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: --timeout 5m
          reporter: ${{ env.REPORTER }}
          workdir: ${{ env.TESTS_DIR }}
          fail_on_error: true
          filter_mode: nofilter

  misspell:
    name: reviewdog/misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          reporter: ${{ env.REPORTER }}
          filter_mode: nofilter
          fail_on_error: true

  markdownlint:
    name: reviewdog/markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ env.REPORTER }}
          filter_mode: nofilter
          fail_on_error: true

  tflint:
    name: reviewdog/tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init

      - name: tflint
        uses: reviewdog/action-tflint@v1.17.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ env.REPORTER }}
          filter_mode: nofilter
          fail_on_error: true
          tflint_rulesets: aws
