name: Publish module to artifactory

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  MODULE_NAMESPACE: "vanguard"
  MODULE_NAME: "terraform-example-module"
  VERSION: ${{ github.sha }}

jobs:
  publish-terraform-module:
    name: publish terraform module to artifactory
    runs-on: ubuntu-latest
    steps:
      - name: download zipfile of current sha
        run: |
          curl -L -o ${{ github.sha }}.zip https://github.com/${GITHUB_REPOSITORY#*/}/archive/${{ github.sha }}.zip
