name: Release
on:
  release:
    types: [ published ]

permissions:
  id-token: write
  contents: write

jobs:
  default:
    uses: cloudposse/github-actions-workflows-terraform-module/.github/workflows/release.yml@main
